sudo: false

language: python

python: "3.6"

env:
  matrix:
    - TESTDIR="pip-install-editable-package-with-markers" PIPENV="pipenv"

    - TESTDIR="pip-should-install-editable-packages-with-different-version" PIPENV="pipenv"

    - TESTDIR="pip-should-install-editable-packages-with-same-version" PIPENV="pipenv"

    - TESTDIR="pip-vs-pipenv-speed" PIPENV="pipenv"

    - TESTDIR="pipenv-shouldnt-different-lock-for-different-python-version" PIPENV="pipenv==2018.7.1"
    - TESTDIR="pipenv-shouldnt-different-lock-for-different-python-version" PIPENV="pipenv==11.9.0"
    - TESTDIR="pipenv-shouldnt-different-lock-for-different-python-version" PIPENV="https://github.com/pypa/pipenv/archive/master.zip"
    - TESTDIR="pipenv-shouldnt-different-lock-for-different-python-version" PIPENV="https://github.com/jxltom/pipenv/archive/master.zip"

    - TESTDIR="pipenv-incorrect-constraints-in-lock" PIPENV="pipenv==2018.7.1"
    - TESTDIR="pipenv-incorrect-constraints-in-lock" PIPENV="pipenv==11.9.0"
    - TESTDIR="pipenv-incorrect-constraints-in-lock" PIPENV="https://github.com/pypa/pipenv/archive/master.zip"
    - TESTDIR="pipenv-incorrect-constraints-in-lock" PIPENV="https://github.com/jxltom/pipenv/archive/master.zip"

    - TESTDIR="pipenv-semicolon-in-editable-package" PIPENV="pipenv==2018.7.1"
    - TESTDIR="pipenv-semicolon-in-editable-package" PIPENV="pipenv==11.9.0"
    - TESTDIR="pipenv-semicolon-in-editable-package" PIPENV="https://github.com/pypa/pipenv/archive/master.zip"
    - TESTDIR="pipenv-semicolon-in-editable-package" PIPENV="-e git+https://github.com/jxltom/pipenv.git@9e46fc8#egg=pipenv"

    - TESTDIR="pipenv-semicolon-in-requirements" PIPENV="pipenv==2018.7.1" 
    - TESTDIR="pipenv-semicolon-in-requirements" PIPENV="pipenv==11.9.0"
    - TESTDIR="pipenv-semicolon-in-requirements" PIPENV="https://github.com/pypa/pipenv/archive/master.zip"
    - TESTDIR="pipenv-semicolon-in-requirements" PIPENV="https://github.com/jxltom/pipenv/archive/master.zip"

matrix:
  fast_finish: true

before_script:
  - pip install $(echo $PIPENV)
  - cd "$TESTDIR"

script:
  - |
    set -e;
    if [ "$TESTDIR" = "pip-install-editable-package-with-markers" ]; then
      pipenv run pip install -r requirements-error.txt || exit 0;
      pipenv run pip install -r requirements-ok.txt;
    elif [ "$TESTDIR" = "pip-should-install-editable-packages-with-different-version" ]; then
      pipenv run pip install -r requirements.txt;
      pipenv run pip list | grep 3.7.5;
      pipenv run pip install -r requirements-updated.txt;
      pipenv run pip list | grep 3.8.1;
    elif [ "$TESTDIR" = "pip-should-install-editable-packages-with-same-version" ]; then
      pipenv run pip install -r requirements.txt;
      pipenv run pip install -r requirements.txt | grep -i "successfully installed pytest";
    elif [ "$TESTDIR" = "pip-vs-pipenv-speed" ]; then
      pipenv uninstall --all > /dev/null;
      time pipenv install --deploy > /dev/null;
      pipenv uninstall --all > /dev/null;
      time pipenv install --ignore-pipfile > /dev/null;
      pipenv uninstall --all > /dev/null;
      time pipenv install --deploy --ignore-pipfile > /dev/null;
      pipenv uninstall --all > /dev/null;
      time pipenv sync > /dev/null;
      pipenv uninstall --all > /dev/null;
      time pipenv run pip install -r requirements.txt > /dev/null;

      pipenv uninstall --all > /dev/null;
      pipenv install > /dev/null;
      time pipenv install --deploy > /dev/null;
      pipenv uninstall --all > /dev/null;
      pipenv install > /dev/null;
      time pipenv install --ignore-pipfile > /dev/null;
      pipenv uninstall --all > /dev/null;
      pipenv install > /dev/null;
      time pipenv install --deploy --ignore-pipfile > /dev/null;
      pipenv uninstall --all > /dev/null;
      pipenv install > /dev/null;
      time pipenv sync > /dev/null;
      pipenv uninstall --all > /dev/null;
      pipenv install > /dev/null;
      time pipenv run pip install -r requirements.txt > /dev/null;
    elif [ "$TESTDIR" = "pipenv-shouldnt-different-lock-for-different-python-version" ]; then
      pipenv lock --clear;
      grep pathlib2 Pipfile.lock;
    elif [ "$TESTDIR" = "pipenv-incorrect-constraints-in-lock" ]; then
      pipenv lock --clear;
    elif [ "$TESTDIR" = "pipenv-semicolon-in-editable-package" ]; then
      pipenv lock --clear;
    elif [ "$TESTDIR" = "pipenv-semicolon-in-requirements" ]; then
      pipenv lock -r > requirements.txt;
      pip install -r requirements.txt;
    fi
